name: reusable-deploy
on:
  workflow_call:
    inputs:
      dummy:
        description: Provide a dummy text to log
        required: true
        type: string
jobs:
  deploy-by-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Output dummy
        run: echo "${{inputs.dummy}}"
